
-- Insert 20 AWS questions and answers
INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_option) VALUES
('What does EC2 stand for?', 
 'Elastic Cloud Compute', 
 'Elastic Compute Cloud', 
 'Elastic Container Service', 
 'Elastic Cloud Storage', 
 'B'),
('Which AWS service is used for object storage?', 
 'EBS', 
 'S3', 
 'EC2', 
 'RDS', 
 'B'),
('What is the default limit of S3 buckets per account?', 
 '50', 
 '100', 
 '200', 
 '500', 
 'B'),
('Which service provides managed database instances?', 
 'RDS', 
 'DynamoDB', 
 'S3', 
 'Lambda', 
 'A'),
('What is the primary purpose of AWS Lambda?', 
 'Hosting static websites', 
 'Running code without provisioning servers', 
 'Data storage', 
 'Load balancing', 
 'B'),
('Which service is used to manage API gateways?', 
 'API Gateway', 
 'AWS Lambda', 
 'CloudFront', 
 'S3', 
 'A'),
('What does VPC stand for?', 
 'Virtual Private Cloud', 
 'Virtual Public Cloud', 
 'Virtual Protected Cloud', 
 'Virtual Private Center', 
 'A'),
('Which AWS service is used for content delivery?', 
 'CloudFront', 
 'S3', 
 'RDS', 
 'EC2', 
 'A'),
('Which of the following is a NoSQL database service provided by AWS?', 
 'RDS', 
 'DynamoDB', 
 'Aurora', 
 'Redshift', 
 'B'),
('What is the AWS service for managing access to resources?', 
 'IAM', 
 'EC2', 
 'S3', 
 'CloudWatch', 
 'A'),
('What does EBS stand for?', 
 'Elastic Block Store', 
 'Elastic Blob Storage', 
 'Elastic Backup Service', 
 'Elastic Bandwidth Service', 
 'A'),
('Which AWS service provides a serverless compute platform?', 
 'EC2', 
 'Lambda', 
 'ECS', 
 'EBS', 
 'B'),
('What is the maximum size of an object in S3?', 
 '5 GB', 
 '10 GB', 
 '50 GB', 
 '5 TB', 
 'D'),
('Which AWS service is used for machine learning?', 
 'SageMaker', 
 'EC2', 
 'RDS', 
 'DynamoDB', 
 'A'),
('What does CloudFormation do?', 
 'Manages user permissions', 
 'Automates resource provisioning', 
 'Stores data', 
 'Monitors resources', 
 'B'),
('What is Amazon''s content delivery network called?', 
 'CloudFront', 
 'CloudTrail', 
 'CloudSearch', 
 'CloudWatch', 
 'A'),
('Which AWS service can be used to run containerized applications?', 
 'ECS', 
 'RDS', 
 'S3', 
 'EC2', 
 'A'),
('What is the main function of AWS CloudTrail?', 
 'Monitor API calls', 
 'Store backups', 
 'Provide analytics', 
 'Manage permissions', 
 'A'),
('Which service provides scalable email sending?', 
 'SES', 
 'SNS', 
 'SQS', 
 'CloudWatch', 
 'A'),
('What is the primary use of Amazon Redshift?', 
 'Data storage', 
 'Data warehousing', 
 'Data processing', 
 'Data analytics', 
 'B');

-- Commit the transaction
COMMIT;
